### PR TITLE
catch mollie state created in payment state updater

### PR DESCRIPTION
**Pull request by Oldharlem**

### CODE REVIEW

**Comment by vernondegoede** [comment]
This should not work, since Mollie will not call the webhook for the `created` status change: https://docs.mollie.com/orders/status-changes#created.

Why would you like to add a debug message for this Order status change?

**Comment by vernondegoede** [comment]
Interesting, it seems like the webhook will be called after all. I'll update the api-documentation to reflect this.

However, showing a log message will not fix the issue described in #45, as nothing will happen with the payment.

**Comment by Oldharlem** [comment]
The problem is that when the webhook calls the api and updates the payment, the created state is not recognised and will revert the order back to state payment and erase the completed_at date.

The debug message was in line with all the other state transition methods so i added it for convention, is not necessary in my opinion indeed.

**Comment by vernondegoede** [comment]
You're right. LGTM! 🚢

**Pull request merged**
